# Generated by Django 6.0.5 on 2026-05-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('Normal', 'Normal'), ('Borderline', 'Borderline'), ('Critical', 'Critical')], default='Normal', max_length=50)),
                ('type', models.CharField(choices=[('Reminder', 'Reminder'), ('Alert', 'Alert')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Upcoming', 'Upcoming'), ('History', 'History')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='family.familymember')),
            ],
        ),
    ]
