# Generated by Django 6.0.5 on 2026-08-25 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('reports', '0002_report_file_report_ocr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='reports.report'),
        ),
    ]
