# Generated by Django 6.0.5 on 2026-08-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
