# Generated by Django 6.0.5 on 2026-05-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Blood', 'Blood'), ('Imaging', 'Imaging'), ('Prescription', 'Prescription'), ('Discharge', 'Discharge')], max_length=50)),
                ('abnormality', models.CharField(choices=[('Normal', 'Normal'), ('Borderline', 'Borderline'), ('Critical', 'Critical')], default='Normal', max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('lab_values', models.JSONField(blank=True, help_text='Stored as a list of dictionaries', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='family.familymember')),
            ],
        ),
    ]
