# Generated by Django 6.0.5 on 2026-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Raw text extracted by OCR', null=True),
        ),
    ]
