# Generated by Django 6.0.5 on 2026-08-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_file_report_ocr_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=100)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_low', models.FloatField(blank=True, null=True)),
                ('reference_high', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reports.report')),
            ],
        ),
    ]
