services:
  - type: web
    name: nexolith-care-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: nexolith-care-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: nexolith-care-db
    databaseName: nexolith_care
    user: postgres
