# Generated by Django 6.0.5 on 2026-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Dependent', 'Dependent'), ('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Other', 'Other')], max_length=50),
        ),
    ]
