# Generated by Django 6.0.5 on 2026-08-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_familymember_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
