# Generated by Django 6.0.5 on 2026-08-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_cleanup_dicebear_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='family_members/'),
        ),
    ]
